### ISSUE TITLE
New Property: Seat Preference

### ISSUE THREAD

**Issue by philsturgeon** [bump-sh-examples/train-travel-api#24]
Add to schema, and filter parameters.

```
seat_preference:
          type: string
          enum: [window, aisle, any]
          example: "window"
```
